Repository codesquad-member-2020/sidedish-10, pull requests merged in 2020-04, with the labels that each got.

#16 [FE] 캐러셀 컴포넌트
  FE/.storybook/addons.js
  FE/.storybook/config.js
  FE/package-lock.json
  FE/package.json
  FE/src/App.css
  FE/src/App.js
  FE/src/components/Carousel/Carousel.css
  FE/src/components/Carousel/Carousel.jsx
  FE/src/components/Carousel/Panel/Panel.css
  FE/src/components/Carousel/Panel/Panel.jsx
  FE/src/components/Carousel/Panel/Profile/Profile.css
  FE/src/components/Carousel/Panel/Profile/Profile.jsx
  FE/src/components/test.js
  FE/src/mockData/imgs/bona.jpg
  FE/src/mockData/imgs/irene.jpg
  FE/src/mockData/imgs/jiae.jpg
  FE/src/mockData/imgs/jisu.jpg
  FE/src/mockData/imgs/joy.jpg
  FE/src/mockData/imgs/luda2.jpg
  FE/src/mockData/imgs/luda3.jpg
  FE/src/mockData/imgs/minju.jpg
  FE/src/mockData/imgs/nauen.jpg
  FE/src/mockData/imgs/rachel.jpg
  FE/src/mockData/imgs/seula.jpg
  FE/src/mockData/imgs/seulgi.jpg
  FE/src/mockData/imgs/seungyeon.jpg
  FE/src/stories/Carousel.stories.jsx
Labels: fe 리뷰요청, front-end

#24 [#11] Network 연결
  iOS/SideDish/.Podfile.swp
  iOS/SideDish/SideDish.xcodeproj/project.pbxproj
  iOS/SideDish/SideDish/Controller/SideDishUseCase.swift
  iOS/SideDish/SideDish/DetailView/DetailViewController.swift
  iOS/SideDish/SideDish/Info.plist
  iOS/SideDish/SideDish/MainMenuView/MainMenuHeaderCell.swift
  iOS/SideDish/SideDish/MainMenuView/MainMenuTableViewCell.swift
  iOS/SideDish/SideDish/MainMenuView/MainMenuViewController.swift
  iOS/SideDish/SideDish/MainMenuView/MainMenuViewDataSource.swift
  iOS/SideDish/SideDish/Model/NetworkManager.swift
  iOS/SideDish/SideDish/Model/SideDish.swift
  iOS/SideDish/SideDish/Model/SideDishManager.swift
  iOS/SideDish/SideDish/Resource/Assets.xcassets/SpecialPriceColor.colorset/Contents.json
  iOS/SideDish/SideDish/StoryBoard/Base.lproj/Main.storyboard
Labels: feature

#29 [iOS] Toaster
  iOS/SideDish/.gitignore
  iOS/SideDish/SideDish.xcodeproj/project.pbxproj
  iOS/SideDish/SideDish/DetailView/DetailViewController.swift
  iOS/SideDish/SideDish/MainMenuView/MainMenuHeader.swift
  iOS/SideDish/SideDish/MainMenuView/MainMenuHeaderCell.swift
  iOS/SideDish/SideDish/MainMenuView/MainMenuTableViewCell.swift
  iOS/SideDish/SideDish/MainMenuView/MainMenuViewController.swift
  iOS/SideDish/SideDish/MainMenuView/PaddingLabel.swift
Labels: feature

#33 [#30] 피드백 반영
  iOS/SideDish/SideDish/Controller/SideDishUseCase.swift
  iOS/SideDish/SideDish/MainMenuView/MainMenuHeader.swift
  iOS/SideDish/SideDish/MainMenuView/MainMenuTableViewCell.swift
  iOS/SideDish/SideDish/MainMenuView/MainMenuViewController.swift
  iOS/SideDish/SideDish/MainMenuView/MainMenuViewDataSource.swift
  iOS/SideDish/SideDish/Model/NetworkManager.swift
Labels: refactor

#37 [BE] Basic JSON Parser, OAuth2 features implemented
  BE/.gitignore
  BE/build.gradle
  BE/gradle/wrapper/gradle-wrapper.jar
  BE/gradle/wrapper/gradle-wrapper.properties
  BE/gradlew
  BE/gradlew.bat
  BE/settings.gradle
  BE/src/main/java/com/codesquad/sidedish10/Sidedish10Application.java
  BE/src/main/java/com/codesquad/sidedish10/getter/config/WebMvcConfigurerImpl.java
  BE/src/main/java/com/codesquad/sidedish10/getter/controller/GetterController.java
  BE/src/main/java/com/codesquad/sidedish10/getter/controller/LoginController.java
  BE/src/main/java/com/codesquad/sidedish10/getter/domain/GitHubToken.java
  BE/src/main/java/com/codesquad/sidedish10/getter/domain/User.java
  BE/src/main/java/com/codesquad/sidedish10/getter/domain/UserRepository.java
  BE/src/main/java/com/codesquad/sidedish10/getter/dto/BabChanDetailDto.java
  BE/src/main/java/com/codesquad/sidedish10/getter/dto/BabChanDetailRepository.java
  BE/src/main/java/com/codesquad/sidedish10/getter/dto/BabChanItemRepository.java
  BE/src/main/java/com/codesquad/sidedish10/getter/dto/BabChanItemRequestDto.java
  BE/src/main/java/com/codesquad/sidedish10/getter/dto/BabChanItemResponseDto.java
  BE/src/main/java/com/codesquad/sidedish10/getter/exception/ErrorCodes.java
  BE/src/main/java/com/codesquad/sidedish10/getter/exception/ExceptionHandler.java
  BE/src/main/java/com/codesquad/sidedish10/getter/exception/JsonNotFoundException.java
  BE/src/main/java/com/codesquad/sidedish10/getter/exception/JwtMissingException.java
  BE/src/main/java/com/codesquad/sidedish10/getter/exception/RudimentaryException.java
  BE/src/main/java/com/codesquad/sidedish10/getter/exception/UserNotFoundException.java
  BE/src/main/java/com/codesquad/sidedish10/getter/interceptor/HttpInterceptor.java
  BE/src/main/java/com/codesquad/sidedish10/getter/service/GetterService.java
  BE/src/main/java/com/codesquad/sidedish10/getter/service/JwtService.java
  BE/src/main/java/com/codesquad/sidedish10/getter/service/LoginService.java
  BE/src/main/java/com/codesquad/sidedish10/getter/utils/ApiResponse.java
  BE/src/main/java/com/codesquad/sidedish10/getter/utils/IndexCollection.java
  BE/src/main/java/com/codesquad/sidedish10/getter/utils/OAuth2SecurityInfo.java
  BE/src/main/java/com/codesquad/sidedish10/parser/controller/parserController.java
  BE/src/main/java/com/codesquad/sidedish10/parser/domain/BabChanDetailObject.java
  BE/src/main/java/com/codesquad/sidedish10/parser/domain/BabChanObject.java
  BE/src/main/java/com/codesquad/sidedish10/parser/domain/ParserRepository.java
  BE/src/main/java/com/codesquad/sidedish10/parser/service/ParseService.java
  BE/src/main/java/com/codesquad/sidedish10/parser/utils/URLJsonParser.java
  BE/src/main/resources/application-deploy.properties
  BE/src/main/resources/application-dev.properties
  BE/src/main/resources/application.properties
  BE/src/main/resources/data.sql
  BE/src/main/resources/schema.sql
  BE/src/test/java/com/codesquad/sidedish10/Sidedish10ApplicationTests.java
Labels: BE

#38 Feature i os/setup detail view ui
  iOS/SideDish/SideDish/Controller/ImageUseCase.swift
  iOS/SideDish/SideDish/Controller/SideDishUseCase.swift
  iOS/SideDish/SideDish/LoginView/LoginViewController.swift
  iOS/SideDish/SideDish/MainMenuView/MainMenuViewController.swift
  iOS/SideDish/SideDish/MainMenuView/MainMenuViewDataSource.swift
  iOS/SideDish/SideDish/Model/NetworkManager.swift
  iOS/SideDish/SideDish/StoryBoard/Base.lproj/Main.storyboard
Labels: feature

#39 [BE] OAuth2 에러핸들 처리, 프론트/iOS 요구사항 구현
  BE/src/main/java/com/codesquad/sidedish10/getter/controller/GetterController.java
  BE/src/main/java/com/codesquad/sidedish10/getter/controller/LoginController.java
  BE/src/main/java/com/codesquad/sidedish10/getter/dto/BabChanItemResponseDto.java
  BE/src/main/java/com/codesquad/sidedish10/getter/dto/BabChanSectionInfoDto.java
  BE/src/main/java/com/codesquad/sidedish10/getter/exception/ExceptionHandler.java
  BE/src/main/java/com/codesquad/sidedish10/getter/exception/RudimentaryException.java
  BE/src/main/java/com/codesquad/sidedish10/getter/repository/BabChanDetailRepository.java
  BE/src/main/java/com/codesquad/sidedish10/getter/repository/BabChanItemRepository.java
  BE/src/main/java/com/codesquad/sidedish10/getter/repository/BabChanSectionInfoRepository.java
  BE/src/main/java/com/codesquad/sidedish10/getter/repository/UserRepository.java
  BE/src/main/java/com/codesquad/sidedish10/getter/response/ApiResponse.java
  BE/src/main/java/com/codesquad/sidedish10/getter/response/ApiResponseForItem.java
  BE/src/main/java/com/codesquad/sidedish10/getter/service/GetterService.java
  BE/src/main/java/com/codesquad/sidedish10/getter/service/LoginService.java
  BE/src/main/java/com/codesquad/sidedish10/parser/domain/ParserRepository.java
  BE/src/main/java/com/codesquad/sidedish10/parser/service/ParseService.java
  BE/src/main/resources/data.sql
  BE/src/main/resources/schema.sql
Labels: BE

#40 [#4] feat: 메뉴 레이어 구현
  FE/package-lock.json
  FE/package.json
  FE/src/App.js
  FE/src/components/Header/Menu/menu.jsx
  FE/src/components/Header/Menu/menuData.js
  FE/src/components/Header/Menu/subMenu.jsx
  FE/src/components/Header/header.jsx
Labels: front-end

#46 [BE] 상세 아이템 보기 API 1차 구현
  BE/src/main/java/com/codesquad/sidedish10/getter/controller/GetterController.java
  BE/src/main/java/com/codesquad/sidedish10/getter/domain/BabChanDetailReturnObject.java
  BE/src/main/java/com/codesquad/sidedish10/getter/dto/BabChanDetailDto.java
  BE/src/main/java/com/codesquad/sidedish10/getter/repository/BabChanDetailRepository.java
  BE/src/main/java/com/codesquad/sidedish10/getter/repository/BabChanItemRepository.java
  BE/src/main/java/com/codesquad/sidedish10/getter/service/GetterService.java
Labels: BE

#47 [BE] 2020.04.28 중간 업데이트 사항 반영을 위한 PR
  BE/src/main/java/com/codesquad/sidedish10/getter/config/WebMvcConfigurerImpl.java
  BE/src/main/java/com/codesquad/sidedish10/getter/controller/GetterController.java
  BE/src/main/java/com/codesquad/sidedish10/getter/controller/LoginController.java
  BE/src/main/java/com/codesquad/sidedish10/getter/domain/BabChanDetailReturnObject.java
  BE/src/main/java/com/codesquad/sidedish10/getter/dto/BabChanDetailDto.java
  BE/src/main/java/com/codesquad/sidedish10/getter/interceptor/SimpleCorsFilter.java
  BE/src/main/java/com/codesquad/sidedish10/getter/repository/BabChanDetailRepository.java
  BE/src/main/java/com/codesquad/sidedish10/getter/repository/BabChanItemRepository.java
  BE/src/main/java/com/codesquad/sidedish10/getter/service/GetterService.java
  BE/src/main/java/com/codesquad/sidedish10/getter/utils/OAuth2SecurityInfo.java
  BE/src/main/resources/application-deploy.properties
Labels: BE

#50 [BE] 밥찬 세부 정보 보여주는 페이지 API 구현
  BE/src/main/java/com/codesquad/sidedish10/getter/config/WebMvcConfigurerImpl.java
  BE/src/main/java/com/codesquad/sidedish10/getter/controller/GetterController.java
  BE/src/main/java/com/codesquad/sidedish10/getter/controller/LoginController.java
  BE/src/main/java/com/codesquad/sidedish10/getter/domain/BabChanDetailReturnObject.java
  BE/src/main/java/com/codesquad/sidedish10/getter/dto/BabChanDetailDto.java
  BE/src/main/java/com/codesquad/sidedish10/getter/interceptor/SimpleCorsFilter.java
  BE/src/main/java/com/codesquad/sidedish10/getter/repository/BabChanDetailRepository.java
  BE/src/main/java/com/codesquad/sidedish10/getter/repository/BabChanItemRepository.java
  BE/src/main/java/com/codesquad/sidedish10/getter/service/GetterService.java
  BE/src/main/java/com/codesquad/sidedish10/getter/utils/OAuth2SecurityInfo.java
  BE/src/main/resources/application-deploy.properties
Labels: back-end, feature

#52 [iOS] set up detailView UI
  iOS/SideDish/SideDish.xcodeproj/project.pbxproj
  iOS/SideDish/SideDish/Controller/DetailInfoUseCase.swift
  iOS/SideDish/SideDish/Controller/ImageUseCase.swift
  iOS/SideDish/SideDish/DetailView/DetailViewController.swift
  iOS/SideDish/SideDish/LoginView/LoginViewController.swift
  iOS/SideDish/SideDish/MainMenuView/MainMenuTableViewCell.swift
  iOS/SideDish/SideDish/MainMenuView/MainMenuViewController.swift
  iOS/SideDish/SideDish/Model/DetailDish.swift
  iOS/SideDish/SideDish/Model/NetworkManager.swift
  iOS/SideDish/SideDish/Model/SideDish.swift
  iOS/SideDish/SideDish/Model/UIColorExtension.swift
  iOS/SideDish/SideDish/Resource/Assets.xcassets/divisionColor.colorset/Contents.json
  iOS/SideDish/SideDish/StoryBoard/Base.lproj/Main.storyboard
Labels: feature

#54 [BE] 각각의 반찬 아이템 재고를 알려주기 위해 하드코딩하였다.
  BE/src/main/java/com/codesquad/sidedish10/getter/controller/GetterController.java
  BE/src/main/java/com/codesquad/sidedish10/getter/dto/BabChanOrderDto.java
  BE/src/main/java/com/codesquad/sidedish10/getter/repository/BabChanDetailRepository.java
  BE/src/main/java/com/codesquad/sidedish10/getter/service/GetterService.java
  BE/src/main/resources/schema.sql
Labels: BE, database
